#!/bin/bash
# See docs/api.md for what this starts and how to use it once running.
#
# Usage:
#   ./run.sh                  # install + start on 127.0.0.1:8000
#   HOST=0.0.0.0 PORT=9000 ./run.sh
#   ./run.sh --host 0.0.0.0 --port 9000

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VENV_DIR=".venv"
RUN_DIR=".run"
SECRETS_FILE="$RUN_DIR/secrets.env"
DB_FILE="$RUN_DIR/starrocks_br_api.db"

HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8000}"

while [ $# -gt 0 ]; do
    case "$1" in
        --host) HOST="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: $0 [--host HOST] [--port PORT]"
            echo "Env overrides: HOST, PORT"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

echo "== starrocks-br API: local setup =="

# --- 1. Python virtualenv -------------------------------------------------

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtualenv at $VENV_DIR..."
    python3 -m venv "$VENV_DIR"
else
    echo "Reusing existing virtualenv at $VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

# --- 2. Dependencies -------------------------------------------------------

echo "Installing starrocks-br..."
pip install --quiet --upgrade pip
pip install --quiet -e .

# --- 3. Secrets --------------------------------------------------------

mkdir -p "$RUN_DIR"

if [ ! -f "$SECRETS_FILE" ]; then
    echo "Generating local API secrets (first run) -> $SECRETS_FILE"
    api_key="$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")"
    encryption_key="$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")"
    cat > "$SECRETS_FILE" <<EOF
# Generated by run.sh. Local-dev secrets only - do not commit or reuse in production.
STARROCKS_BR_API_KEY=$api_key
STARROCKS_BR_DB_ENCRYPTION_KEY=$encryption_key
EOF
    chmod 600 "$SECRETS_FILE"
else
    echo "Reusing existing secrets from $SECRETS_FILE"
fi

# shellcheck disable=SC1090
set -a
source "$SECRETS_FILE"
set +a

export STARROCKS_BR_DATABASE_URL="${STARROCKS_BR_DATABASE_URL:-sqlite:///$SCRIPT_DIR/$DB_FILE}"

# --- 4. Metadata store migrations ------------------------------------------

echo "Applying metadata store migrations (DATABASE_URL=$STARROCKS_BR_DATABASE_URL)..."
alembic upgrade head

# --- 5. Start the server ----------------------------------------------------

echo ""
echo "== Starting API server on http://$HOST:$PORT =="
echo "   API key (also saved in $SECRETS_FILE):"
echo "     $STARROCKS_BR_API_KEY"
echo ""
echo "   Try in another terminal:"
echo "     curl -H \"Authorization: Bearer $STARROCKS_BR_API_KEY\" http://$HOST:$PORT/clusters"
echo ""
echo "   Full reference: docs/api.md"
echo ""

exec uvicorn starrocks_br.api.app:create_app --factory --host "$HOST" --port "$PORT"
