"""move ops tables into sqlite

Revision ID: 059d2b79d525
Revises: 9bf7a7f90f78
Create Date: 2026-09-25 12:37:07.794274

Moves the 5 ops bookkeeping tables (table_inventory, backup_history,
restore_history, run_status, backup_partitions) from a per-cluster StarRocks
database into this metastore, scoped by cluster_id, and drops the
now-unused clusters.ops_database column. No production data exists yet, so
this is a clean cutover with no data migration.

Note on downgrade(): the re-added `ops_database` column uses a
server_default purely for schema symmetry (so the column is immediately
usable without an app-level default). The original column never had a
server_default - only a Python-side default in the ORM model - so this is a
deliberate deviation from a true reversal, not a restoration of prior state.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059d2b79d525'
down_revision: str | Sequence[str] | None = '9bf7a7f90f78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('backup_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'label', name='uq_backup_history_cluster_label')
    )
    op.create_index(op.f('ix_backup_history_cluster_id'), 'backup_history', ['cluster_id'], unique=False)
    op.create_table('backup_partitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('partition_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'key_hash', name='uq_backup_partitions_cluster_key_hash')
    )
    op.create_index(op.f('ix_backup_partitions_cluster_id'), 'backup_partitions', ['cluster_id'], unique=False)
    op.create_index('ix_backup_partitions_cluster_label', 'backup_partitions', ['cluster_id', 'label'], unique=False)
    op.create_table('restore_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('backup_label', sa.String(length=255), nullable=False),
    sa.Column('restore_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('verification_checksum', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'job_id', name='uq_restore_history_cluster_job')
    )
    op.create_index(op.f('ix_restore_history_cluster_id'), 'restore_history', ['cluster_id'], unique=False)
    op.create_table('run_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'scope', 'label', name='uq_run_status_cluster_scope_label')
    )
    op.create_index(op.f('ix_run_status_cluster_id'), 'run_status', ['cluster_id'], unique=False)
    op.create_index('ix_run_status_cluster_scope_state', 'run_status', ['cluster_id', 'scope', 'state'], unique=False)
    op.create_table('table_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('inventory_group', sa.String(length=128), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'inventory_group', 'database_name', 'table_name', name='uq_table_inventory_membership')
    )
    op.create_index('ix_table_inventory_cluster_group', 'table_inventory', ['cluster_id', 'inventory_group'], unique=False)
    op.create_index(op.f('ix_table_inventory_cluster_id'), 'table_inventory', ['cluster_id'], unique=False)
    op.drop_column('clusters', 'ops_database')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'clusters',
        sa.Column('ops_database', sa.VARCHAR(length=128), nullable=False, server_default='ops'),
    )
    op.drop_index(op.f('ix_table_inventory_cluster_id'), table_name='table_inventory')
    op.drop_index('ix_table_inventory_cluster_group', table_name='table_inventory')
    op.drop_table('table_inventory')
    op.drop_index('ix_run_status_cluster_scope_state', table_name='run_status')
    op.drop_index(op.f('ix_run_status_cluster_id'), table_name='run_status')
    op.drop_table('run_status')
    op.drop_index(op.f('ix_restore_history_cluster_id'), table_name='restore_history')
    op.drop_table('restore_history')
    op.drop_index('ix_backup_partitions_cluster_label', table_name='backup_partitions')
    op.drop_index(op.f('ix_backup_partitions_cluster_id'), table_name='backup_partitions')
    op.drop_table('backup_partitions')
    op.drop_index(op.f('ix_backup_history_cluster_id'), table_name='backup_history')
    op.drop_table('backup_history')
    # ### end Alembic commands ###
