"""baseline schema

Revision ID: b7bf2d5f2365
Revises: 
Create Date: 2026-09-27 13:13:04.670056

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7bf2d5f2365'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('default_backend', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=True)
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('backup_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'label', name='uq_backup_history_cluster_label')
    )
    op.create_index(op.f('ix_backup_history_cluster_id'), 'backup_history', ['cluster_id'], unique=False)
    op.create_table('backup_partitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('partition_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'key_hash', name='uq_backup_partitions_cluster_key_hash')
    )
    op.create_index(op.f('ix_backup_partitions_cluster_id'), 'backup_partitions', ['cluster_id'], unique=False)
    op.create_index('ix_backup_partitions_cluster_label', 'backup_partitions', ['cluster_id', 'label'], unique=False)
    op.create_table('inventory_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name', name='uq_inventory_groups_cluster_name')
    )
    op.create_index(op.f('ix_inventory_groups_cluster_id'), 'inventory_groups', ['cluster_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('state_detail', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_cluster_id'), 'jobs', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_jobs_group_id'), 'jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('restore_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('backup_label', sa.String(length=255), nullable=False),
    sa.Column('restore_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('verification_checksum', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'job_id', name='uq_restore_history_cluster_job')
    )
    op.create_index(op.f('ix_restore_history_cluster_id'), 'restore_history', ['cluster_id'], unique=False)
    op.create_table('run_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'scope', 'label', name='uq_run_status_cluster_scope_label')
    )
    op.create_index(op.f('ix_run_status_cluster_id'), 'run_status', ['cluster_id'], unique=False)
    op.create_index('ix_run_status_cluster_scope_state', 'run_status', ['cluster_id', 'scope', 'state'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('inventory_group_id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('cadence', sa.String(length=128), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['inventory_group_id'], ['inventory_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_run_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_cluster_id'), 'schedules', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_schedules_inventory_group_id'), 'schedules', ['inventory_group_id'], unique=False)
    op.create_table('table_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('inventory_group_id', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_group_id'], ['inventory_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'inventory_group_id', 'database_name', 'table_name', name='uq_table_inventory_membership')
    )
    op.create_index('ix_table_inventory_cluster_group', 'table_inventory', ['cluster_id', 'inventory_group_id'], unique=False)
    op.create_index(op.f('ix_table_inventory_cluster_id'), 'table_inventory', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_inventory_cluster_id'), table_name='table_inventory')
    op.drop_index('ix_table_inventory_cluster_group', table_name='table_inventory')
    op.drop_table('table_inventory')
    op.drop_index(op.f('ix_schedules_inventory_group_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_cluster_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_run_status_cluster_scope_state', table_name='run_status')
    op.drop_index(op.f('ix_run_status_cluster_id'), table_name='run_status')
    op.drop_table('run_status')
    op.drop_index(op.f('ix_restore_history_cluster_id'), table_name='restore_history')
    op.drop_table('restore_history')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_group_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_cluster_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_inventory_groups_cluster_id'), table_name='inventory_groups')
    op.drop_table('inventory_groups')
    op.drop_index('ix_backup_partitions_cluster_label', table_name='backup_partitions')
    op.drop_index(op.f('ix_backup_partitions_cluster_id'), table_name='backup_partitions')
    op.drop_table('backup_partitions')
    op.drop_index(op.f('ix_backup_history_cluster_id'), table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
